version: '3.8'

services:
  frontend:
    build:
      context: ./lunch-vote-frontend  # Ensure this directory exists in your project root
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000
    volumes:
      - ./lunch-vote-frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000  # Reference backend service in Docker
    depends_on:
      - backend

  backend:
    build:
      context: ./lunch-vote-backend  # Ensure this directory exists in your project root
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - ./lunch-vote-backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/lunchvote  # Database connection
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lunchvote
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
